name: nasa_images
description: NASA gallery app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  injectable: ^1.5.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  i69n: ^2.1.0
  freezed_annotation: ^1.1.0
  flutter_svg: ^1.0.0
  auto_route: ^3.2.1
  google_fonts: ^2.2.0
  dio: ^4.0.4
  retrofit: ^3.0.1
  json_annotation: ^4.4.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.2.1
  retrofit_generator: ^3.0.1+1
  freezed: ^1.1.0
  extra_pedantic: ^1.5.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Glory-Regular
      fonts:
        - asset: assets/fonts/Glory-Regular.ttf

    - family: Glory-SemiBold
      fonts:
        - asset: assets/fonts/Glory-SemiBold.ttf

    - family: Nasa
      fonts:
        - asset: assets/fonts/Nasa.ttf
