name: nasa_images
description: NASA gallery app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  get_it: ^7.2.0
  injectable: ^1.5.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.1
  i69n: ^2.0.1
  freezed_annotation: ^0.15.0
  flutter_svg: ^0.23.0+1
  auto_route: ^3.0.3
  google_fonts: ^2.1.0
  dio: ^4.0.1
  retrofit: ^2.0.1
  json_annotation: ^4.3.0
  dartz: ^0.10.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  injectable_generator: ^1.5.2
  auto_route_generator: ^3.0.1
  retrofit_generator: ^2.0.1+2
  freezed: ^0.15.0+1
  extra_pedantic: ^1.5.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Glory-Regular
      fonts:
        - asset: assets/fonts/Glory-Regular.ttf

    - family: Glory-SemiBold
      fonts:
        - asset: assets/fonts/Glory-SemiBold.ttf

    - family: Nasa
      fonts:
        - asset: assets/fonts/Nasa.ttf
